repos:
  - repo: https://github.com/akaihola/darker
    rev: master
    hooks:
      - id: darker
        args: [deerlab, -i, -v, -r origin/main...]
        additional_dependencies:
          - black~=21.8b0
          - isort~=5.9