ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: weekly
    skip: []
    submodules: false

repos:
  - repo: https://github.com/akaihola/darker
    rev: 1.4.2
    hooks:
      - id: darker
        verbose: true
        args: [--isort, -v, -r origin/main...]
        additional_dependencies:
          - black~=21.8b0
          - isort~=5.9