from sympy import false


[tool.darker]
src = [
    "./deerlab",
]
revision = "origin/main..."
isort = true
check = false
diff = false
log_level = "INFO"
verbose=true 
lint = [
    "flake8",
]

[tool.isort]
profile = "black"
