name: 'Publish Conda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, modified by Maxime Borry, modified by Luis Fabregas'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
  platforms:
    description: 'Platforms to build and publish [osx linux win]'
    default: 'win-64 osx-64 linux-64'
  python:
    description: 'Python version to build and publish'
    default: '3.8'
runs:
  using: 'docker'
  image: 'Dockerfile'
