package:
  name: deerlab
  version: VERSION

source:
  git_rev: VERSION
  git_url: https://github.com/JeschkeLab/DeerLab.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - memoization
    - matplotlib
    - tqdm
    - joblib
    - numpy
    - scipy
    - cvxopt
    - dill
    - pytest

about:
  home: https://jeschkelab.github.io/DeerLab/index.html
  license: MIT
  summary: 'Comprehensive package for data analysis of dipolar EPR spectroscopy'
  description: |
    DeerLab is a comprehensive free scientific software package for Python focused on modelling,
    penalized least-squares regression, and uncertainty quantification. It provides highly 
    specialized on the analysis of dipolar EPR (electron paramagnetic resonance) spectroscopy data. 
    Dipolar EPR spectroscopy techniques include DEER (double electron-electron resonance), 
    RIDME (relaxation-induced dipolar modulation enhancement), and others. 
  dev_url: https://jeschkelab.github.io/DeerLab
