{% set version = "v0.13.0" %}

package:
  name: deerlab
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/JeschkeLab/DeerLab.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - memoization
    - matplotlib
    - tqdm
    - joblib
    - numpy
    - scipy
    - cvxopt

about:
  home: https://jeschkelab.github.io/DeerLab/index.html
  license: MIT
  summary: 'Comprehensive package for data analysis of dipolar EPR spectroscopy'
  description: |
    DeerLab is a Python package for the analysis of dipolar EPR (electron paramagnetic resonance)
    spectroscopy data. Dipolar EPR spectroscopy techniques include DEER (double electron-electron resonance),
    RIDME (relaxation-induced dipolar modulation enhancement), and others.
    DeerLab consists of a collection of functions for modelling, data processing, and least-squares fitting.
    They can be combined in scripts to build custom data analysis workflows. DeerLab supports both classes of 
    distance distribution models: non-parametric (Tikhonov regularization and related) and parametric 
    (multi-Gaussians etc). It also provides a selection of background and experiment models.
  dev_url: https://jeschkelab.github.io/DeerLab
