name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - uses: akaihola/darker@master
        with:
          options: "-v --isort --diff"
          src: "./deerlab"
