name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - uses: akaihola/darker@1.4.2
        with:
          options: "--check --diff --isort"
          revision: "main..."
          src: "./deerlab"
          lint: "flake8,pylint==2.13.1"