name: Test documentation examples build PR

on:
  pull_request:
    branches:
      - "**"
    paths:
      - 'examples/**'
      - '.github/workflows/deploy_ghpages.yml'
      - '.github/workflows/docs_PR.yml'
      - '.github/workflows/examples_PR.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docsbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install furo numpydoc sphinx-gallery sphinxcontrib-httpdomain sphinxcontrib-ghcontributors sphinx-issues sphinx-copybutton sphinx sphinx-design .
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Build with Sphinx
        run: sphinx-build -E -b html ./docsrc/source ./docs
