name: Build & Upload Python Package

on: 
  release:
    types: [published]

jobs:

  pypi-build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install pypa/build
      run: >-
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m build --sdist --wheel --outdir dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
          
  conda-build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Get DeerLab version
      run: echo "DEERLAB_VERSION=$(cat VERSION)" >> $GITHUB_ENV
    - name: Update version in Conda metadata 
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "VERSION"
        replace: ${{env.DEERLAB_VERSION}}
        include: "conda.recipe/meta.yaml" 
    - name: Build & Publish to Anaconda
      uses: ./.github/actions/conda_build_publish_package
      with:
        subdir: 'conda.recipe'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'osx-64 linux-32 linux-64 win-32 win-64'
        python: '3.8 3.9 3.10'